name: enumerator_macro
description: A starting point for Dart libraries or applications.
version: 0.0.1-dev.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-216.1.beta

# Add regular dependencies here.
# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
